/*
 * LoginWindow.java
 *
 * Created on 12 de abril de 2003, 11:11 AM
 */

package py.edu.uca.fcyt.util;


/**
 *
 * @author  PABLO JAVIER
 */
public class LoginPanel extends javax.swing.JPanel {
    
    private String username;
    
    private String password;
    
    /** Creates new form LoginWindow */
    public LoginPanel() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jpUsername = new javax.swing.JPanel();
        jlUsername = new javax.swing.JLabel();
        jtUsername = new javax.swing.JTextField();
        jpPassword = new javax.swing.JPanel();
        jlPassword = new javax.swing.JLabel();
        jpfPassword = new javax.swing.JPasswordField();
        jpButtons = new javax.swing.JPanel();
        jbConectar = new javax.swing.JButton();
        jbCancelar = new javax.swing.JButton();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        jlUsername.setText("Jugador:");
        jpUsername.add(jlUsername);

        jtUsername.setPreferredSize(new java.awt.Dimension(100, 20));
        jpUsername.add(jtUsername);

        add(jpUsername);

        jlPassword.setText("Password:");
        jpPassword.add(jlPassword);

        jpfPassword.setPreferredSize(new java.awt.Dimension(100, 20));
        jpPassword.add(jpfPassword);

        add(jpPassword);

        jbConectar.setText("Conectar");
        jbConectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbConectarActionPerformed(evt);
            }
        });

        jpButtons.add(jbConectar);

        jbCancelar.setText("Cancelar");
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });

        jpButtons.add(jbCancelar);

        add(jpButtons);

    }//GEN-END:initComponents

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
        // Add your handling code here:
        setUsername("");
        setPassword("");
        setVisible(false);
        //JOptionPane.getRootFrame().setVisible(false);
        
    }//GEN-LAST:event_jbCancelarActionPerformed
    
    
    private void jbConectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbConectarActionPerformed
        // Add your handling code here:
        setUsername(jtUsername.getText());
        setPassword(String.valueOf(jpfPassword.getPassword()));
        setVisible(false);
        //JOptionPane.getRootFrame().setVisible(false);
    }//GEN-LAST:event_jbConectarActionPerformed

    /** Getter for property password.
     * @return Value of property password.
     *
     */
    public java.lang.String getPassword() {
        return password;
    }    
    
    /** Setter for property password.
     * @param password New value of property password.
     *
     */
    public void setPassword(java.lang.String password) {
        this.password = password;
    }    
    
    /** Getter for property username.
     * @return Value of property username.
     *
     */
    public java.lang.String getUsername() {
        return username;
    }
    
    /** Setter for property username.
     * @param username New value of property username.
     *
     */
    public void setUsername(java.lang.String username) {
        this.username = username;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jpButtons;
    private javax.swing.JLabel jlUsername;
    private javax.swing.JButton jbConectar;
    private javax.swing.JPanel jpUsername;
    private javax.swing.JPanel jpPassword;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JTextField jtUsername;
    private javax.swing.JLabel jlPassword;
    private javax.swing.JPasswordField jpfPassword;
    // End of variables declaration//GEN-END:variables
    
}
