/*
 * LoginDialog.java
 *
 * Created on 12 de abril de 2003, 03:48 PM
 */

package py.edu.uca.fcyt.util;

import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
/**
 *
 * @author  PABLO JAVIER
 */
public class LoginDialog extends javax.swing.JDialog {
    LoginPanel loginPanel;
    /** Creates new form LoginDialog */
    public LoginDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        loginPanel = new LoginPanel();
        loginPanel.addComponentListener(new ComponentAdapter() {
            public void componentHidden(ComponentEvent e) {
                System.out.println("Component was hidden!");
                setVisible(false);
            }
        });
        getContentPane().add(loginPanel);
        pack();
    }
    
    public String getUsername() {
        return loginPanel.getUsername();
    }
    
    public String getPassword() {
        return loginPanel.getPassword();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });
        
        pack();
    }//GEN-END:initComponents
    
    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new LoginDialog(new javax.swing.JFrame(), true).show();
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
}
