/*
 * RoomUI.java
 *
 * Created on 15 de abril de 2003, 08:09 PM
 */

package py.edu.uca.fcyt.toluca;

import javax.swing.*;

import py.edu.uca.fcyt.toluca.game.*;
import py.edu.uca.fcyt.game.*;


/**
 *
 * @author  PABLO JAVIER
 */
public class RoomUI extends javax.swing.JApplet {
    
    private ChatPanel chatPanel;
    private JButtonTable mainTable;
    private RankingTable rankTable;
    private RoomClient roomClient;
    
    /** Creates new form RoomUI */
    public RoomUI() {
        initComponents();
        
        
        mainTable = new JButtonTable();
        rankTable = new RankingTable();
        System.out.println("Agregar el mainTable");
        jpTabla.add(mainTable);
        System.out.println("Agregar el rankTable");
        if (rankTable ==null) System.out.println("Es nulo el rankTaaaaable!!!");
        jpRanking.add(rankTable);
 
        login();
        
    }
    
    public void login() {
        // El login lo escribo por n-ésima vez - CVS urgeeeeente!
        py.edu.uca.fcyt.util.LoginDialog ld = new py.edu.uca.fcyt.util.LoginDialog(JOptionPane.getRootFrame(), true);
        ld.show();
        roomClient = new RoomClient(this, ld.getUsername(), ld.getPassword());
        //chatPanel = new ChatPanel(roomClient);
        //jpChat.add(chatPanel);
        //roomClient.setChatPanel(chatPanel);
        roomClient.setMainTable(mainTable);
        roomClient.setRankTable(rankTable);
        
    }
    
    public void addChatPanel(ChatPanel cp) {
        jpChat.add(cp);
        jpChat.validate();
    }
    
    public void init() {
        
    }
    
    public void start() {
        
    }
    
    public void stop() {
        
    }
    
    public void destroy() {
        
    }

     /** <p>
     * Does ...
     * </p><p>
     *
     * @param player ...
     * </p><p>
     * @param htmlMessage ...
     * </p><p>
     *
     * </p>
     *
     */
    public void sendChatMessage(Player player, String htmlMessage) {
    }    
    
    public void showChatMessage(Player player, String htmlMessage) {
    }    
    
    /** Getter for property chatPanel.
     * @return Value of property chatPanel.
     *
     */
    public ChatPanel getChatPanel() {
        return chatPanel;
    }
    
    /** Setter for property chatPanel.
     * @param chatPanel New value of property chatPanel.
     *
     */
    public void setChatPanel(ChatPanel chatPanel) {
        this.chatPanel = chatPanel;
    }
    
    /** Getter for property mainTable.
     * @return Value of property mainTable.
     *
     */
    public py.edu.uca.fcyt.toluca.JButtonTable getMainTable() {
        return mainTable;
    }
    
    /** Setter for property mainTable.
     * @param mainTable New value of property mainTable.
     *
     */
    public void setMainTable(py.edu.uca.fcyt.toluca.JButtonTable mainTable) {
        this.mainTable = mainTable;
    }
    
    /** Getter for property rankTable.
     * @return Value of property rankTable.
     *
     */
    public py.edu.uca.fcyt.toluca.RankingTable getRankTable() {
        return rankTable;
    }
    
    /** Setter for property rankTable.
     * @param rankTable New value of property rankTable.
     *
     */
    public void setRankTable(py.edu.uca.fcyt.toluca.RankingTable rankTable) {
        this.rankTable = rankTable;
    }
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jpBotones = new javax.swing.JPanel();
        jbUno = new javax.swing.JButton();
        jpTabla = new javax.swing.JPanel();
        jpChatRanking = new javax.swing.JPanel();
        jpChat = new javax.swing.JPanel();
        jpRanking = new javax.swing.JPanel();

        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        jbUno.setText("jButton1");
        jpBotones.add(jbUno);

        getContentPane().add(jpBotones);

        getContentPane().add(jpTabla);

        jpChatRanking.setLayout(new javax.swing.BoxLayout(jpChatRanking, javax.swing.BoxLayout.X_AXIS));

        jpChatRanking.add(jpChat);

        jpChatRanking.add(jpRanking);

        getContentPane().add(jpChatRanking);

    }//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jpBotones;
    private javax.swing.JPanel jpChat;
    private javax.swing.JPanel jpChatRanking;
    private javax.swing.JPanel jpTabla;
    private javax.swing.JButton jbUno;
    private javax.swing.JPanel jpRanking;
    // End of variables declaration//GEN-END:variables
    
}
