/*
 * RoomUI2.java
 *
 * Created on May 8, 2003, 1:08 AM
 */

package py.edu.uca.fcyt.toluca;

import javax.swing.JOptionPane;

import py.edu.uca.fcyt.game.ChatPanel;
import py.edu.uca.fcyt.toluca.game.TrucoPlayer;

/**
 * 
 * @author Interfaz de Inicio
 * @deprecated Usar RoomUING
 */
public class RoomUI extends javax.swing.JApplet {

    private ChatPanel chatPanel;

    private JButtonTable mainTable;

    private RankingTable rankTable;

    private RoomClient roomClient;

    /** Creates new form RoomUI2 */
    public RoomUI() {
        initComponents();
        custInitComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jpLogo = new javax.swing.JPanel();
        jpMain = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jpBotones = new javax.swing.JPanel();
        jbCreateTable = new javax.swing.JButton();
        jbJoin = new javax.swing.JButton();
        jpTabla = new javax.swing.JPanel();
        jpChatRanking = new javax.swing.JPanel();
        jpRanking = new javax.swing.JPanel();
        jpChat = new javax.swing.JPanel();

        getContentPane().setLayout(
                new javax.swing.BoxLayout(getContentPane(),
                        javax.swing.BoxLayout.Y_AXIS));

        jpLogo.setBackground(new java.awt.Color(0, 0, 0));
        jpLogo.setToolTipText("Toluca");
        jpLogo.setPreferredSize(new java.awt.Dimension(10, 70));
        getContentPane().add(jpLogo);

        jpMain.setLayout(new javax.swing.BoxLayout(jpMain,
                javax.swing.BoxLayout.Y_AXIS));

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1,
                javax.swing.BoxLayout.X_AXIS));

        jPanel1.setBackground(new java.awt.Color(102, 153, 0));
        jpBotones.setLayout(new javax.swing.BoxLayout(jpBotones,
                javax.swing.BoxLayout.Y_AXIS));

        jbCreateTable.setBackground(new java.awt.Color(204, 204, 0));
        jbCreateTable.setFont(new java.awt.Font("Dialog", 0, 10));
        jbCreateTable.setForeground(new java.awt.Color(102, 102, 0));
        jbCreateTable.setText("Create Table");
        jbCreateTable.setMaximumSize(new java.awt.Dimension(100, 20));
        jbCreateTable.setMinimumSize(new java.awt.Dimension(100, 20));
        jbCreateTable.setPreferredSize(new java.awt.Dimension(100, 20));
        jbCreateTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCreateTableActionPerformed(evt);
            }
        });

        jpBotones.add(jbCreateTable);

        jbJoin.setBackground(new java.awt.Color(204, 204, 0));
        jbJoin.setFont(new java.awt.Font("Dialog", 1, 10));
        jbJoin.setForeground(new java.awt.Color(102, 102, 0));
        jbJoin.setText("Join");
        jbJoin.setMaximumSize(new java.awt.Dimension(100, 20));
        jbJoin.setMinimumSize(new java.awt.Dimension(100, 20));
        jbJoin.setPreferredSize(new java.awt.Dimension(100, 20));
        jbJoin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbJoinActionPerformed(evt);
            }
        });

        jpBotones.add(jbJoin);

        jPanel1.add(jpBotones);

        jpTabla.setBackground(new java.awt.Color(102, 153, 0));
        jPanel1.add(jpTabla);

        jpMain.add(jPanel1);

        jpChatRanking.setLayout(new javax.swing.BoxLayout(jpChatRanking,
                javax.swing.BoxLayout.X_AXIS));

        jpChatRanking.setBackground(new java.awt.Color(204, 204, 0));
        jpRanking.setBackground(new java.awt.Color(102, 153, 0));
        jpChatRanking.add(jpRanking);

        jpChat.setLayout(new javax.swing.BoxLayout(jpChat,
                javax.swing.BoxLayout.X_AXIS));

        jpChatRanking.add(jpChat);

        jpMain.add(jpChatRanking);

        getContentPane().add(jpMain);

    }//GEN-END:initComponents

    private void jbJoinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbJoinActionPerformed
        // aca se mira si el player selecciono alguna mesa para jugar
        int numeroDeFila = mainTable.isRowSelected();
        System.out.println("numeroDeFila=" + numeroDeFila);
        if (numeroDeFila >= 0) {
            numeroDeFila = mainTable.getNumeroDeMesa(numeroDeFila);
            System.out.println("////////////// JOINNN /////////////");
            System.out.println("Se presiono el join..." + numeroDeFila);
            roomClient.joinTableRequest(numeroDeFila);
        }
    }//GEN-LAST:event_jbJoinActionPerformed

    private void jbCreateTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCreateTableActionPerformed
        // Add your handling code here:
        roomClient.createTableRequest();
    }//GEN-LAST:event_jbCreateTableActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jpBotones;

    private javax.swing.JPanel jpLogo;

    private javax.swing.JPanel jpChat;

    private javax.swing.JButton jbCreateTable;

    private javax.swing.JPanel jpChatRanking;

    private javax.swing.JPanel jpTabla;

    private javax.swing.JPanel jPanel1;

    private javax.swing.JPanel jpMain;

    private javax.swing.JButton jbJoin;

    private javax.swing.JPanel jpRanking;

    // End of variables declaration//GEN-END:variables

    private void custInitComponents() {

        mainTable = new JButtonTable();
        rankTable = new RankingTable();
        System.out.println("Agregar el mainTable.");
        jpTabla.add(mainTable);
        System.out.println("Agregar el rankTable.");
        if (rankTable == null)
            System.out.println("Es nulo el rankTaaaaable!!!");
        jpRanking.add(rankTable);

        login();
    }

    public void login() {
        // El login lo escribo por n-ésima vez - CVS urgeeeeente!
        /*py.edu.uca.fcyt.util.LoginDialog ld = new py.edu.uca.fcyt.util.LoginDialog(
                JOptionPane.getRootFrame(), true);
        ld.show();
        roomClient = new RoomClient(this, ld.getUsername(), ld.getPassword());
        chatPanel = new ChatPanel(roomClient);
        jpChat.add(chatPanel);
        roomClient.setChatPanel(chatPanel);
        roomClient.setMainTable(mainTable);
        roomClient.setRankTable(rankTable);*/

        // esto es para probar nomas, sacar despues!!
        //Table table = new Table();
        //table.setTableNumber(5);
        //mainTable.insertarFila(table);

        jpChatRanking.validate();
    }

    public void addChatPanel(ChatPanel cp) {
        System.out.println("Esto se ejecuta sin falta!");
        //jpChat.add(new JLabel("Berniii"));
        jpChat.removeAll();
        jpChat.add(cp);
        jpChat.validate();
        //jpChat.repaint();
        //System.out.println("Se terminó de agregar el cp: " +
        // cp.getPlayer().getName());

        //validate();
        //repaint();
    }

    public void init() {

    }

    public void start() {

    }

    public void stop() {

    }

    public void destroy() {
        System.out.println("El player cerro su RoomUI!");
        roomClient.eliminatePlayer();
    }

    /**
     * <p>
     * Does ...
     * </p>
     * <p>
     * 
     * @param player
     *            ...
     *            </p>
     *            <p>
     * @param htmlMessage
     *            ...
     *            </p>
     *            <p>
     * 
     * </p>
     *  
     */
    public void sendChatMessage(TrucoPlayer player, String htmlMessage) {
    }

    public void showChatMessage(TrucoPlayer player, String htmlMessage) {
    }

    /**
     * Getter for property chatPanel.
     * 
     * @return Value of property chatPanel.
     *  
     */
    public ChatPanel getChatPanel() {
        return chatPanel;
    }

    /**
     * Setter for property chatPanel.
     * 
     * @param chatPanel
     *            New value of property chatPanel.
     *  
     */
    public void setChatPanel(ChatPanel chatPanel) {
        this.chatPanel = chatPanel;
    }

    /**
     * Getter for property mainTable.
     * 
     * @return Value of property mainTable.
     *  
     */
    public py.edu.uca.fcyt.toluca.JButtonTable getMainTable() {
        return mainTable;
    }

    /**
     * Setter for property mainTable.
     * 
     * @param mainTable
     *            New value of property mainTable.
     *  
     */
    public void setMainTable(py.edu.uca.fcyt.toluca.JButtonTable mainTable) {
        this.mainTable = mainTable;
    }

    /**
     * Getter for property rankTable.
     * 
     * @return Value of property rankTable.
     *  
     */
    public py.edu.uca.fcyt.toluca.RankingTable getRankTable() {
        return rankTable;
    }

    /**
     * Setter for property rankTable.
     * 
     * @param rankTable
     *            New value of property rankTable.
     *  
     */
    public void setRankTable(py.edu.uca.fcyt.toluca.RankingTable rankTable) {
        this.rankTable = rankTable;
    }

}