/*
 * RoomUI2.java
 *
 * Created on May 8, 2003, 1:08 AM
 */

package py.edu.uca.fcyt.toluca;

import javax.swing.*;

import py.edu.uca.fcyt.toluca.game.*;
import py.edu.uca.fcyt.game.*;

/**
 *
 * @author  Owner
 */
public class RoomUI extends javax.swing.JApplet
{
    
    private ChatPanel chatPanel;
    private JButtonTable mainTable;
    private RankingTable rankTable;
    private RoomClient roomClient;
    
    /** Creates new form RoomUI2 */
    public RoomUI()
    {
	initComponents();
	custInitComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jpMain = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jpBotones = new javax.swing.JPanel();
        jbUno = new javax.swing.JButton();
        jbCreateTable = new javax.swing.JButton();
        jSPtabla = new javax.swing.JScrollPane();
        jpTabla = new javax.swing.JPanel();
        jpChatRanking = new javax.swing.JPanel();
        jSPrank = new javax.swing.JScrollPane();
        jpRanking = new javax.swing.JPanel();
        jpChat = new javax.swing.JPanel();

        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        jpMain.setLayout(new javax.swing.BoxLayout(jpMain, javax.swing.BoxLayout.Y_AXIS));

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.X_AXIS));

        jpBotones.setLayout(new javax.swing.BoxLayout(jpBotones, javax.swing.BoxLayout.Y_AXIS));

        jbUno.setFont(new java.awt.Font("Dialog", 1, 10));
        jbUno.setText("Play Now");
        jbUno.setMaximumSize(new java.awt.Dimension(100, 20));
        jbUno.setMinimumSize(new java.awt.Dimension(100, 20));
        jbUno.setPreferredSize(new java.awt.Dimension(100, 20));
        jpBotones.add(jbUno);

        jbCreateTable.setFont(new java.awt.Font("Dialog", 0, 10));
        jbCreateTable.setText("Create Table");
        jbCreateTable.setMaximumSize(new java.awt.Dimension(100, 20));
        jbCreateTable.setMinimumSize(new java.awt.Dimension(100, 20));
        jbCreateTable.setPreferredSize(new java.awt.Dimension(100, 20));
        jbCreateTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCreateTableActionPerformed(evt);
            }
        });

        jpBotones.add(jbCreateTable);

        jPanel1.add(jpBotones);

        jSPtabla.setViewportView(jpTabla);

        jPanel1.add(jSPtabla);

        jpMain.add(jPanel1);

        jpChatRanking.setLayout(new javax.swing.BoxLayout(jpChatRanking, javax.swing.BoxLayout.X_AXIS));

        jSPrank.setViewportView(jpRanking);

        jpChatRanking.add(jSPrank);

        jpChat.setLayout(new javax.swing.BoxLayout(jpChat, javax.swing.BoxLayout.X_AXIS));

        jpChatRanking.add(jpChat);

        jpMain.add(jpChatRanking);

        getContentPane().add(jpMain);

    }//GEN-END:initComponents

    private void jbCreateTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCreateTableActionPerformed
        // Add your handling code here:
        roomClient.createTableRequest();
    }//GEN-LAST:event_jbCreateTableActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jpBotones;
    private javax.swing.JScrollPane jSPrank;
    private javax.swing.JPanel jpChat;
    private javax.swing.JButton jbCreateTable;
    private javax.swing.JPanel jpChatRanking;
    private javax.swing.JPanel jpTabla;
    private javax.swing.JScrollPane jSPtabla;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbUno;
    private javax.swing.JPanel jpMain;
    private javax.swing.JPanel jpRanking;
    // End of variables declaration//GEN-END:variables
    
    private void custInitComponents()
    {
	
	mainTable = new JButtonTable();
        rankTable = new RankingTable();
        System.out.println("Agregar el mainTable");
        jpTabla.add(mainTable);
        System.out.println("Agregar el rankTable");
        if (rankTable ==null) System.out.println("Es nulo el rankTaaaaable!!!");
        jpRanking.add(rankTable);
 
        login();
    }
    
    public void login() {
        // El login lo escribo por n-ésima vez - CVS urgeeeeente!
        py.edu.uca.fcyt.util.LoginDialog ld = new py.edu.uca.fcyt.util.LoginDialog(JOptionPane.getRootFrame(), true);
        ld.show();
        roomClient = new RoomClient(this, ld.getUsername(), ld.getPassword());
        chatPanel = new ChatPanel(roomClient);
        jpChat.add(chatPanel);
        roomClient.setChatPanel(chatPanel);
        roomClient.setMainTable(mainTable);
        roomClient.setRankTable(rankTable);
        
    }
    
    public void addChatPanel(ChatPanel cp) {
        System.out.println("Esto se ejecuta sin falta!");
        //jpChat.add(new JLabel("Berniii"));
        jpChat.removeAll();
        jpChat.add(cp);
        jpChat.validate();
        //jpChat.repaint();
        //System.out.println("Se terminó de agregar el cp: " + cp.getPlayer().getName());
        
        //validate();
        //repaint();
    }
    
    public void init() {
        
    }
    
    public void start() {
        
    }
    
    public void stop() {
        
    }
    
    public void destroy() {
        
    }

     /** <p>
     * Does ...
     * </p><p>
     *
     * @param player ...
     * </p><p>
     * @param htmlMessage ...
     * </p><p>
     *
     * </p>
     *
     */
    public void sendChatMessage(Player player, String htmlMessage) {
    }    
    
    public void showChatMessage(Player player, String htmlMessage) {
    }    
    
    /** Getter for property chatPanel.
     * @return Value of property chatPanel.
     *
     */
    public ChatPanel getChatPanel() {
        return chatPanel;
    }
    
    /** Setter for property chatPanel.
     * @param chatPanel New value of property chatPanel.
     *
     */
    public void setChatPanel(ChatPanel chatPanel) {
        this.chatPanel = chatPanel;
    }
    
    /** Getter for property mainTable.
     * @return Value of property mainTable.
     *
     */
    public py.edu.uca.fcyt.toluca.JButtonTable getMainTable() {
        return mainTable;
    }
    
    /** Setter for property mainTable.
     * @param mainTable New value of property mainTable.
     *
     */
    public void setMainTable(py.edu.uca.fcyt.toluca.JButtonTable mainTable) {
        this.mainTable = mainTable;
    }
    
    /** Getter for property rankTable.
     * @return Value of property rankTable.
     *
     */
    public py.edu.uca.fcyt.toluca.RankingTable getRankTable() {
        return rankTable;
    }
    
    /** Setter for property rankTable.
     * @param rankTable New value of property rankTable.
     *
     */
    public void setRankTable(py.edu.uca.fcyt.toluca.RankingTable rankTable) {
        this.rankTable = rankTable;
    }
    
}
