/*
 * ChatPanel.java
 *
 * Created on 12 de abril de 2003, 09:54 AM
 */

package py.edu.uca.fcyt.game;

import java.awt.Font;

import javax.swing.DefaultListModel;
import javax.swing.JFrame;

import py.edu.uca.fcyt.toluca.game.TrucoPlayer;

/**
 *
 * @author  PABLO JAVIER
 */
public class ChatPanel extends javax.swing.JPanel {
    private ChatPanelContainer cpc;
    private TrucoPlayer player;
    private DefaultListModel dlm;
    
    public ChatPanel() {
        initComponents();
    }
    
    

    public ChatPanel(ChatPanelContainer cpc) {
        this();
        setCpc(cpc);        
    }
    
    /** Creates new form ChatPanel */
    public ChatPanel(ChatPanelContainer cpc, TrucoPlayer player) {
        if (player == null) {
            new Exception("Se fue a la puta: player null").printStackTrace(System.out);
            //            System.out.println("El player es null :((");
        } else {
            //            System.out.println("TrucoPlayer BZ!: " + player.getName());
        }
        setPlayer(player);
        setCpc(cpc);
        initComponents();
    }
    
    public void showChatMessage(TrucoPlayer player, String htmlMessage) {
        jTAchat.append
        (
        player.getName() + ": " + htmlMessage + "\n"
        );
        jTAchat.setCaretPosition(jTAchat.getText().length());
    }
    
    public void showChatMessage(TrucoPlayer player, String htmlMessage, String[] bounds) {
        if (bounds == null) bounds = new String[] { "**", "**"};
        jTAchat.append(
        bounds[0] + player.getName() + bounds[1] + ": "
        + htmlMessage + "\n"
        );
        jTAchat.setCaretPosition(jTAchat.getText().length());
    }
    
    private void sendChatMessage() {
        
        System.out.println(getClass().getName()+" getplayer "+getPlayer());
        cpc.sendChatMessage(getPlayer(), jtInput.getText());
        jtInput.setText("");
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents()//GEN-BEGIN:initComponents
    {
        jpInput = new javax.swing.JPanel();
        jtInput = new javax.swing.JTextField();
        Send = new javax.swing.JButton();
        jpChat = new javax.swing.JPanel();
        jspChat = new javax.swing.JScrollPane();
        jTAchat = new javax.swing.JTextArea();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        setPreferredSize(new java.awt.Dimension(200, 100));
        jpInput.setLayout(new javax.swing.BoxLayout(jpInput, javax.swing.BoxLayout.X_AXIS));

        jtInput.setPreferredSize(new java.awt.Dimension(300, 20));
        jtInput.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                jtInputKeyPressed(evt);
            }
        });

        jpInput.add(jtInput);

        Send.setText("Send");
        Send.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                SendActionPerformed(evt);
            }
        });

        jpInput.add(Send);

        add(jpInput);

        jpChat.setLayout(new javax.swing.BoxLayout(jpChat, javax.swing.BoxLayout.X_AXIS));

        jspChat.setPreferredSize(new java.awt.Dimension(350, 320));
        jTAchat.setEditable(false);
        jTAchat.setFont(new java.awt.Font("SansSerif", Font.PLAIN, 10));
        jTAchat.setLineWrap(true);
        jTAchat.setToolTipText("null");
        jTAchat.setWrapStyleWord(true);
        jspChat.setViewportView(jTAchat);

        jpChat.add(jspChat);

        add(jpChat);

    }//GEN-END:initComponents
    
    private void jtInputKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jtInputKeyPressed
    {//GEN-HEADEREND:event_jtInputKeyPressed
        // Add your handling code here:
        if(evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER)
            sendChatMessage();
    }//GEN-LAST:event_jtInputKeyPressed
    
    private void SendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SendActionPerformed
        // Add your handling code here:
        sendChatMessage();
    }//GEN-LAST:event_SendActionPerformed
    
    /** Getter for property cpc.
     * @return Value of property cpc.
     *
     */
    public ChatPanelContainer getCpc() {
        return cpc;
    }
    
    /** Setter for property cpc.
     * @param cpc New value of property cpc.
     *
     */
    public void setCpc(ChatPanelContainer cpc) {
        this.cpc = cpc;
    }
    
    /** Getter for property player.
     * @return Value of property player.
     *
     */
    public TrucoPlayer getPlayer() {
        return player;
    }
    
    /** Setter for property player.
     * @param player New value of property player.
     *
     */
    public void setPlayer(TrucoPlayer player) {
    	System.out.println("ChatPanel.setPlayer: Se setea el player "+player);
        this.player = player;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Send;
    private javax.swing.JTextField jtInput;
    private javax.swing.JPanel jpInput;
    private javax.swing.JPanel jpChat;
    private javax.swing.JTextArea jTAchat;
    private javax.swing.JScrollPane jspChat;
    // End of variables declaration//GEN-END:variables
    
    public static void main(String[] args) {
        TrucoPlayer pepito = new TrucoPlayer("Don Pepito", 8);
        TrucoPlayer jose = new TrucoPlayer("Don Jos�", 8);
        ChatPanel cp = new ChatPanel(null, pepito);
        JFrame jf = new JFrame("Chat paaaaaanel!");
        jf.getContentPane().add(cp);
        jf.pack();
        jf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        jf.show();
        //        cp.showChatMessage(jose, "Hola don Pepito");
        //        cp.showChatMessage(pepito, "Hola don Jos�");
    }
}
